Algoritmo "Funcao Para de ate Faca"

// Descrição   : Estudo da função para de até faça
// Autor(a)    : BrunoP
// Data atual  : 27/06/2026

Var

   numero: inteiro

Inicio

      // Para <Variável Contadora> de <Valor Inicial> ate <Valor Final> Faca

      // Instruções a serem executadas repetidamente até a <Variávl Contadora> atingir o <Valor Final>

      // FimPara

      Para numero de 1 ate 10 Faca
      
           escreval("Número: ", numero)
           
      FimPara

Fimalgoritmo