Algoritmo "Tipos de Dados"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/06/2026
Var

   quantidade : inteiro
   preco : real
   totalAPagar : real
   produto : caractere
   cliente : caractere
   compraEfetuada : logico

Inicio

   quantidade <- 2
   preco <- 67,69
   totalAPagar <- quantidade * preco
   produto <- "anel de prata 18k"
   cliente <- "Giovana"
   compraEfetuada <- VERDADEIRO

   escreval (quantidade)
   escreval (preco)
   escreval (totalAPagar)
   escreval (produto)
   escreval (cliente)
   escreval (compraEfetuada)
   escreval
   escreval
   escreval ("A cliente ", cliente, " comprou ", quantidade, " ", produto, " que estavam custando R$", preco, " cada, pagando um total de R$", totalAPagar, " quando a compra foi efetuada como ", compraEfetuada, ".")
   escreval




Fimalgoritmo