Algoritmo "Olá Mundo!"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/06/2026
Var
// Seção de Declarações das variáveis 


Inicio
              // o comando "escreva" com "l" no final (escreval) faz a quebra do texto para a linha de baixo.
              
      escreval ("Olá Mundo!")
      escreval ("Feijão com farinha?")
      escreval
      escreval
      
      escreva ("Olá Mundo! 1")
      escreva ("Feijão com farinha? 1")


Fimalgoritmo