Algoritmo "Funcao Se com E"

// Descrição   : Estudo da Função Se com E
// Autor(a)    : BrunoP
// Data atual  : 21/06/2026

Var

   numero: inteiro

Inicio

   escreval ("Digite um número: ")
   leia (numero)
   escreval

   Se (numero >= 2) e (numero <=10) Entao
      escreval ("O número", numero, " está dentro do intervalo de 2 a 10!")

   Senao
      escreval ("O número", numero, " está fora do intervalo de 2 a 1o!")

   Fimse

   escreval
   escreval

Fimalgoritmo