Algoritmo "Função Se com Ou"

// Descrição   : Estudo da função Se com Ou
// Autor(a)    : BrunoP
// Data atual  : 21/06/2026

Var

   cor: caracter


Inicio

      escreval ("Digite uma cor: ")
      leia (cor)
      escreval
      
      Se (cor = "azul") ou (cor = "amarelo") entao
         escreval ("A cor digitada é azul ou amarelo!!!")
      
      Senao
           escreval ("Cor inválida T^T")
      
      Fimse
      
      Escreval

Fimalgoritmo