Algoritmo "Função Se ex. 2"

// Descrição   : Estudo da Função Se
// Autor(a)    : BrunoP
// Data atual  : 21/06/2026

Var

   cor: caractere

Inicio

      escreval ("Digite uma cor:")
      leia (cor)
      escreval
      
      Se (cor = "azul") entao
         escreval ("A cor digitada é azul!!!")
         
      Senao
           se (cor = "amarelo") entao
              escreval ("A cor digitada é amarelo!!!")
              
           senao
              escreval ("Cor inválida T-T")
              
           fimse
           
      Fimse
      
      escreval
      escreval

Fimalgoritmo