Algoritmo "Função Se - ex. 1"
// 
//  
// Descrição   : Estudo da função SE
// Autor(a)    : BrunoP
// Data atual  : 21/06/2026
Var

   numero: inteiro

Inicio

      // Se <expressão booleana> Então
      
      //    <instruções a serem executadas caso a expressão booleana resulte em VERDADEIRO>

      // Senão
      
      //    <instruções a serem executadas caso a expressão booleana resulte em FALSO>
      
      // FimSe
      
      //ex.:
      
      escreval ("Digite um número diferente de 10: ")
      leia (numero)
      escreval
      
      se (numero > 10) entao
      
      escreval (numero, " é MAIOR que 10!")
      
      senao
      
      escreval (numero, " é MENOR que 10!")
      
      fimse
      
      escreval
      escreval
      
Fimalgoritmo