Algoritmo "Enquanto Faca numero for diferente de 5"

// Descrição   : Exercício da função enquanto
// Autor(a)    : BrunoP
// Data atual  : 26/06/2026

Var

   Soma, numero: real

Inicio

   Escreval ("Digite um número: ")
   Leia (numero)
   escreval

   Enquanto numero <> 5 Faca

      soma <- soma + numero

      escreval ("Digite outro número: ")
      Leia (numero)
      escreval

   FimEnquanto
   escreval
   Escreval ("Total: ", soma)

   Escreval

Fimalgoritmo