Algoritmo "Funcao Enquanto"

// Descrição   : Estudo da função enquanto
// Autor(a)    : BrunoP
// Data atual  : 26/06/2026

Var

   letra: caractere

Inicio

      // Enquanto <expressão booleana> Faca
      
         // <instruções a serem executadas enquanto a expressão booleana resultar em VERDADEIRO>
         
      // FimEnquanto
      //Ex.:
      
      Enquanto letra <> "A" Faca
      
               Escreval ("Digite uma letra: ")
               Leia (letra)
               escreval
      
      FimEnquanto

                 Escreval ("Você Digitou a letra '", letra,"'! Até a próxima!!!")
                 escreval
                 escreval

Fimalgoritmo