Algoritmo "Repita Ate 50 Numeros Pares"

// Descrição   : Imprimi os 50 primeiros números pares de 2 a 100 usando função a Repita Até.
// Autor(a)    : BPresstes
// Data atual  : 29/06/2026

Var

   numero, i: inteiro

Inicio

      i <- 1
      numero <- 2

      Repita
      
            Escreval(numero)
            numero <- numero + 2
            i <- i + 1

      Ate i > 50
      
      escreval

Fimalgoritmo