Algoritmo "Repita Ate Numero Maior ou Igual a 10"

// Descrição   : Um Algoritmo que imprimi um número de 0 a 10 utilizando a função Repita Até
// Autor(a)    : BPresstes
// Data atual  : 29/06/2026

Var

   numero: inteiro

Inicio

      numero <- 0
      
      Repita
      
            Escreval(numero)
            numero <- numero + 1
            
      Até numero > 10
      
      escreval

Fimalgoritmo